apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone_project_2
  labels:
    app: new_flaskapp
spec:
  selector:
    matchLabels:
      app: new_flaskapp
  replicas: 3
  template:
    metadata:
      labels:
        app: new_flaskapp
    spec:
      containers:
      - name: new_flaskapp
        image: ssrful/new_flaskapp
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: capstone_project_2
spec:
  type: NodePort
  selector:
    app: new_flaskapp
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 35000